name: Build and Package WinForms App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: Restore NuGet Packages
        run: nuget restore PluginConfig.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        run: msbuild PluginConfig.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Create Build Artifact Directory
        run: mkdir -p BuildOutput

      - name: Copy Build Output
        run: |
          $buildOutput = Get-ChildItem -Path . -Recurse -Filter bin | Where-Object { $_.FullName -match "Release" } | Select-Object -ExpandProperty FullName
          Copy-Item -Path "$buildOutput\*" -Destination BuildOutput -Recurse -Force

      - name: Package Build Artifacts
        run: Compress-Archive -Path BuildOutput\* -DestinationPath PluginConfig.zip

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PluginConfig
          path: PluginConfig.zip
